name: '✨ New Bot Command'
description: Requesting a new bot command
title: '✨ <command name>'
labels: [✨ new command]
body:
  - type: markdown
    attributes:
      value: '## Before you continue, please search our open/closed issues to see if a similar issue has been addressed.'

  - type: checkboxes
    attributes:
      label: I have searched through the issues and didn't find my problem.
      options:
        - label: Confirm
          required: true

  - type: textarea
    id: newcommand
    attributes:
      label: New Command
      description: Tell us about this new command, and what it should do.
    validations:
      required: true

  - type: textarea
    id: commanddescription
    attributes:
      label: 'Command details, and why is it useful?'
      description: How would this command work, and why is it useful?
    validations:
      required: true

  - type: textarea
    id: extrainformation
    attributes:
      label: Additional information
      description: Is there anything else we should know about this new command?
